### ISSUE TITLE
JSON structure has been updated - parser no longer handles it correctly

### ISSUE THREAD

**Issue by imakowski** [David-Byrne/Hangons#6]
My Hangouts.json does not have conversation_state in JSON. It has conversations instead. Do yo have version that works with currently exported Hangouts.json?

**Comment by David-Byrne** [comment]
Looks like they've updated the JSON schema used. I'll update the code to match and see if I can get it working. Thanks :smile:

**Comment by David-Byrne** [comment]
They renamed a few fields and changed the internal structure slightly. I've updated the code in 278fc21271069161381bfab9e254929d6e06713f to match the new schema and it works with my takeout file. 

I have a feeling there will be an issue parsing voice messages since I didn't touch that code, but I don't have any to test so I can't figure out the new schema for them.

Thanks for the heads up about the changes
